output:	main_D.o print_D_Node.o add_D_Node.o delete.o
	cc main_D.c print_D_Node.c add_D_Node.c delete.c -o output
main_D.o: main_D.c
	cc -c main_D.c

pint_D_Node.o: print_D_Node.c
	cc -c print_D_Node.c

add_D_Node.o : add_D_Node.c
	cc -c add_D_Node.c
delete.o : delete.c
	cc -c delete.c
